[package]
name = "yew-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
yew-hooks = "0.1.56"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
